name: Build & Deploy

on:
  push:

jobs:
  build:
    strategy:
        matrix:
          os: [ubuntu, macos, windows]
          java-version: [11, 17]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: adopt
      - name: Run quality assurance and test with coverage
        run: ./gradlew clean check
  